### PR TITLE
Update main readme

### PR DESCRIPTION
**Pull request by facumartin-zz**
## Description
This pull request updates the **main** readme of the repository with the following changes:

- Add How it works section, describing the functionality and how are connected the different parts of the stack.
- Architecture diagram updated according to the change of DynamoDB table by S3 bucket file.

## Changes made

- How it works section added
- Architecture diagram updated

## More details
image

image

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Hi @facumartin, how're you?
I placed a little semantic and syntax reviews.

**Review by facumartin-zz — COMMENTED** [review]
Changes proposed by Angel were solved.

**Review by totigm — COMMENTED** [review]
Just some suggestions

**Review by nahuelschlegel — CHANGES_REQUESTED** [review]
I've just suggested some improvements

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by nahuelschlegel — APPROVED** [review]

**Pull request merged**
